### ISSUE TITLE
Can't compile with znc-1.0

### ISSUE THREAD

**Issue by BlueFyre** [fuzzmz/Watch-only-detached-ZNC-module#2]
After the release of znc-1.0 this it no longer builds

**Comment by fuzzmz** [comment]
@BlueFyre, I know this is old as dirt now, but the functionality of this module has been added to the official watch module starting with ZNC 1.6.

See https://github.com/znc/znc/pull/388 and https://github.com/znc/znc/issues/641

**Comment by BlueFyre** [comment]
Thanks
